### Package Installation ###

In [1]:
pip install psycopg2

Requirement already satisfied: psycopg2 in d:\00online\venv\lib\site-packages (2.9.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Requirement already satisfied: pandas in d:\00online\venv\lib\site-packages (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\00online\venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\00online\venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in d:\00online\venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in d:\00online\venv\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in d:\00online\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

### Importing Packages ###

In [3]:
import psycopg2
import pandas as pd
import psycopg2.extras

### Extract ###

#### Read from CSV file ####

In [10]:
import os

notebook_directory = os.getcwd()
parent_directory = os.path.abspath(os.path.join(notebook_directory, os.pardir))
os.chdir(parent_directory)

# Construct the relative path
directory = os.getcwd()
# print("Current", notebook_directory)
relative_path = os.path.join(directory, 'dataset', 'HealthData')
print(relative_path)
os.chdir(relative_path)

file_path = os.path.join(os.getcwd(), 'dim_geography.csv')
geography_data = pd.read_csv(file_path)

D:\00Online\HDA-Buet-vtraining-23\notebook\dataset\Health Datasets

In [26]:
geography_data

     geo_key                 upazila  district division
0     603602              AJMIRIGANJ  HABIGANJ   SYLHET
1     603605                 BAHUBAL  HABIGANJ   SYLHET
2     603611              BANIACHONG  HABIGANJ   SYLHET
3     603626             CHUNARUGHAT  HABIGANJ   SYLHET
4     603644          HABIGANJ SADAR  HABIGANJ   SYLHET
..       ...                     ...       ...      ...
551   107958               MATHBARIA  PIROJPUR  BARISAL
552   107976                NAZIRPUR  PIROJPUR  BARISAL
553   107980          PIROJPUR SADAR  PIROJPUR  BARISAL
554   107987  NESARABAD (SWARUPKATI)  PIROJPUR  BARISAL
555   107990                ZIANAGAR  PIROJPUR  BARISAL

[556 rows x 4 columns]

In [12]:
file_path = os.path.join(os.getcwd(), 'dim_hospital.csv')
hospital_data = pd.read_csv(file_path)

In [13]:
hospital_data

,hospital_key,hospital_name,branch_name,hospital_type,email,website,address,geo_code,city,upazila,district,division
0,100001,BANGLADESH EYE HOSPITAL LTD.,Dhanmondi,Private,info@bdeyehospital.com,www.mysoftltd.com,"78, Satmasjid Road (Road#27), Dhanmondi,",302616,DHAKA,DHANMONDI,DHAKA,DHAKA
1,100002,BANGLADESH EYE HOSPITAL LTD(Mirpur),Mirpur,Private,info@bdeyehospital.com,www.mysoftltd.com,Mirpur,302648,DHAKA,MIRPUR,DHAKA,DHAKA
2,100003,BANGLADESH EYE HOSPITAL LTD(Uttara),Uttara,Private,info@bdeyehospital.com,www.mysoftltd.com,Uttara,302694,DHAKA,UTTARA PASCHIM,DHAKA,DHAKA

In [14]:
file_path = os.path.join(os.getcwd(), 'dim_lab.csv')
lab_data = pd.read_csv(file_path)

In [15]:
lab_data

     lab_key                     lab_name  lab_type lab_code lab_desc
0      10001               ADMINISTRATION         1      679     DESC
1      10002                      Urology         1     0037     DESC
2      10003                     Serology         1     0008     DESC
3      10004            AMBULANCE SERVICE         1     0057     DESC
4      10005                          USG         1     0012     DESC
..       ...                          ...       ...      ...      ...
236    10237  Nursing Service (Technical)         1   BSH096     DESC
237    10238                     MEDICINE         1     MED1     DESC
238    10239                   OPD DOCTOR         1     D002     DESC
239    10240                         Maha         1   Maha01     DESC
240    10241               Oncology test          1     on01     DESC

[241 rows x 5 columns]

In [16]:
file_path = os.path.join(os.getcwd(), 'dim_test.csv')
test_data = pd.read_csv(file_path)

In [17]:
test_data

,test_key,test_name,test_code,specimen,ct_ref,test_desc
0,10002,Pus for Fungus,1988,PUS,BSH,Desc
1,10003,Drain Fluid for Bilirubin,00885,FLUID,BSH,Desc
2,10004,NASAL SWAB FOR KLB,0705,Not Found,BSH,Desc
3,10005,X-Pert MTB/RIF assay by archived gastric Aspi...,0706,TRACHEAL ASPIRATE,BSH,Desc
4,10006,Anti-Filaria Ab IgG4,0192,BLOOD,BSH,Desc
...,...,...,...,...,...,...
1130,10011,Pleural Fluid for Malignant Cell,1486,PLEURAL FLUID,BSH,A malignant pleural effusion (MPE) is the buil...
1131,10693,FBG - Fasting blood glucose,0031,BLOOD,SNOMED CT,Desc
1132,10453,RBG - Random blood glucose,0030,BLOOD,SNOMED CT,Desc
1133,10259,Blood calcium level,0237,BLOOD,SNOMED CT,Desc
1134,10899,Serum creatinine level,0036,BLOOD,SNOMED CT,Desc

In [18]:
file_path = os.path.join(os.getcwd(), 'dim_time.csv')
time_data = pd.read_csv(file_path)

In [19]:
time_data

     time_key   date_time  year  month  day  yyyymm  yyyymmdd quarter
0    20190907  2019-09-07  2019      9    7  201909  20190907      Q3
1    20190908  2019-09-08  2019      9    8  201909  20190908      Q3
2    20190909  2019-09-09  2019      9    9  201909  20190909      Q3
3    20190911  2019-09-11  2019      9   11  201909  20190911      Q3
4    20190912  2019-09-12  2019      9   12  201909  20190912      Q3
..        ...         ...   ...    ...  ...     ...       ...     ...
555  20190318  2019-03-18  2019      3   18  201903  20190318      Q1
556  20190319  2019-03-19  2019      3   19  201903  20190319      Q1
557  20190317  2019-03-17  2019      3   17  201903  20190317      Q1
558  20190320  2019-03-20  2019      3   20  201903  20190320      Q1
559  20190322  2019-03-22  2019      3   22  201903  20190322      Q1

[560 rows x 8 columns]

In [20]:
file_path = os.path.join(os.getcwd(), 'fact_sales.csv')
sales_data = pd.read_csv(file_path)

In [21]:
sales_data
os.chdir(notebook_directory)

,_id,pik,time_key,geo_key,hospital_key,lab_key,test_key,sales_price
0,1,F1926jvorfrrglahvcrnouosvspqsp,20190708,204667,100001,10003,10490,1030
1,2,F1926jvorfrrglahvcrnouosvspqsp,20190708,204667,100001,10043,10156,1210
2,3,F1926jvorfrrglahvcrnouosvspqsp,20190708,204667,100001,10043,10257,430
3,4,F1926jvorfrrglahvcrnouosvspqsp,20190708,204667,100001,10043,10822,1210
4,5,F1926jvorfrrglahvcrnouosvspqsp,20190708,204667,100001,10043,10899,480
...,...,...,...,...,...,...,...,...
92078,92079,M2018xvncrvcrnouoosrrvvn,20200301,302650,100001,10051,10531,1100
92079,92080,M2018xvncrvcrnouoosrrvvn,20200301,302650,100001,10053,10157,850
92080,92081,M2018xvncrvcrnouoosrrvvn,20200301,302650,100001,10058,10617,310
92081,92082,M2018xwrrefhpplrnounruupuws,20190911,207585,100001,10048,10655,400
92082,92083,M2018xwrrefhpplrnounruupuws,20190911,207585,100001,10051,10231,500

### Transform ###

In [30]:
time_data['date_time'] = time_data['date_time'].astype('datetime64[ns]')
time_data.dtypes

time_key              int64
date_time    datetime64[ns]
year                  int64
month                 int64
day                   int64
yyyymm                int64
yyyymmdd              int64
quarter              object
dtype: object

### Load ###

#### Connect to DB ####

In [34]:
class PostgresConnection(object):
    def __init__(self):
        self.connection = psycopg2.connect(database="healthdb",
                                           user = "postgres",
                                           password = "ahanaf12",
                                           host = "127.0.0.1",
                                           port = "5432")

    def getConnection(self):
        print("Connection to DB established!")
        return self.connection

In [35]:
con = PostgresConnection().getConnection()

Connection to DB established!

#### Insert Data into tables #####

In [36]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"geography_dim\"(geo_key, upazila, district, division)" \
            " VALUES (%s, %s, %s, %s)"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, geography_data.values)
con.commit()
cur.close()

Connection to DB established!

In [39]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"hospital_dim\"( hospital_key, hospital_name, branch_name, hospital_type, email, website, address, geo_code, city, upazila, district, division) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, hospital_data.values)
con.commit()
cur.close()

Connection to DB established!

In [41]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"lab_dim\"( lab_key, lab_name, lab_type, lab_code, lab_desc) VALUES (%s, %s, %s, %s, %s);"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, lab_data.values)
con.commit()
cur.close()

Connection to DB established!

In [44]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"test_dim\"(test_key, test_name, test_code, specimen, ct_ref, test_desc)VALUES (%s, %s, %s, %s, %s, %s);"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, test_data.values)
con.commit()
cur.close()

Connection to DB established!

In [45]:
import time

start_time = time.time()

con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"time_dim\"(time_key, date_time, year, month, day, yyyymm, yyyymmdd, quarter)VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, time_data.values)
con.commit()
cur.close()

end_time = time.time()

print("Excecution time: {:.2f} seconds".format(end_time - start_time))

Connection to DB established!
Excecution time: 0.08 seconds

In [46]:
import time

start_time = time.time()

con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO healthdb_schema.\"fact_table\"(_id, pik, time_key, geo_key, hospital_key, lab_key, test_key, sales_price) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, sales_data.values)
con.commit()
cur.close()

end_time = time.time()

print("Excecution time: {:.2f} seconds".format(end_time - start_time))

Connection to DB established!
Excecution time: 8.28 seconds

In [47]:
con = PostgresConnection().getConnection()
select_stmt = "Select * FROM healthdb_schema.\"time_dim\""
cur = con.cursor()
cur.execute(select_stmt)
res = cur.fetchall()
cur.close()

Connection to DB established!

In [48]:
res

[(20190907, '2019-09-07 00:00:00', 2019, 9, 7, '201909', '20190907', 'Q3'),
 (20190908, '2019-09-08 00:00:00', 2019, 9, 8, '201909', '20190908', 'Q3'),
 (20190909, '2019-09-09 00:00:00', 2019, 9, 9, '201909', '20190909', 'Q3'),
 (20190911, '2019-09-11 00:00:00', 2019, 9, 11, '201909', '20190911', 'Q3'),
 (20190912, '2019-09-12 00:00:00', 2019, 9, 12, '201909', '20190912', 'Q3'),
 (20190913, '2019-09-13 00:00:00', 2019, 9, 13, '201909', '20190913', 'Q3'),
 (20190910, '2019-09-10 00:00:00', 2019, 9, 10, '201909', '20190910', 'Q3'),
 (20190918, '2019-09-18 00:00:00', 2019, 9, 18, '201909', '20190918', 'Q3'),
 (20190914, '2019-09-14 00:00:00', 2019, 9, 14, '201909', '20190914', 'Q3'),
 (20190915, '2019-09-15 00:00:00', 2019, 9, 15, '201909', '20190915', 'Q3'),
 (20190916, '2019-09-16 00:00:00', 2019, 9, 16, '201909', '20190916', 'Q3'),
 (20190917, '2019-09-17 00:00:00', 2019, 9, 17, '201909', '20190917', 'Q3'),
 (20190828, '2019-08-28 00:00:00', 2019, 8, 28, '201908', '20190828', 'Q3'),
 (20190829, '2019-08-29 00:00:00', 2019, 8, 29, '201908', '20190829', 'Q3'),
 (20200604, '2020-06-04 00:00:00', 2020, 6, 4, '202006', '20200604', 'Q2'),
 (20200605, '2020-06-05 00:00:00', 2020, 6, 5, '202006', '20200605', 'Q2'),
 (20200603, '2020-06-03 00:00:00', 2020, 6, 3, '202006', '20200603', 'Q2'),
 (20200606, '2020-06-06 00:00:00', 2020, 6, 6, '202006', '20200606', 'Q2'),
 (20200602, '2020-06-02 00:00:00', 2020, 6, 2, '202006', '20200602', 'Q2'),
 (20200601, '2020-06-01 00:00:00', 2020, 6, 1, '202006', '20200601', 'Q2'),
 (20200530, '2020-05-30 00:00:00', 2020, 5, 30, '202005', '20200530', 'Q2'),
 (20200521, '2020-05-21 00:00:00', 2020, 5, 21, '202005', '20200521', 'Q2'),
 (20200531, '2020-05-31 00:00:00', 2020, 5, 31, '202005', '20200531', 'Q2'),
 (20200526, '2020-05-26 00:00:00', 2020, 5, 26, '202005', '20200526', 'Q2'),
 (20200528, '2020-05-28 00:00:00', 2020, 5, 28, '202005', '20200528', 'Q2'),
 (20200519, '2020-05-19 00:00:00', 2020, 5, 19, '202005', '20200519', 'Q2'),
 (20200518, '2020-05-18 00:00:00', 2020, 5, 18, '202005', '20200518', 'Q2'),
 (20200523, '2020-05-23 00:00:00', 2020, 5, 23, '202005', '20200523', 'Q2'),
 (20200520, '2020-05-20 00:00:00', 2020, 5, 20, '202005', '20200520', 'Q2'),
 (20200525, '2020-05-25 00:00:00', 2020, 5, 25, '202005', '20200525', 'Q2'),
 (20200511, '2020-05-11 00:00:00', 2020, 5, 11, '202005', '20200511', 'Q2'),
 (20200510, '2020-05-10 00:00:00', 2020, 5, 10, '202005', '20200510', 'Q2'),
 (20200514, '2020-05-14 00:00:00', 2020, 5, 14, '202005', '20200514', 'Q2'),
 (20200527, '2020-05-27 00:00:00', 2020, 5, 27, '202005', '20200527', 'Q2'),
 (20200517, '2020-05-17 00:00:00', 2020, 5, 17, '202005', '20200517', 'Q2'),
 (20200524, '2020-05-24 00:00:00', 2020, 5, 24, '202005', '20200524', 'Q2'),
 (20200513, '2020-05-13 00:00:00', 2020, 5, 13, '202005', '20200513', 'Q2'),
 (20200509, '2020-05-09 00:00:00', 2020, 5, 9, '202005', '20200509', 'Q2'),
 (20200512, '2020-05-12 00:00:00', 2020, 5, 12, '202005', '20200512', 'Q2'),
 (20200522, '2020-05-22 00:00:00', 2020, 5, 22, '202005', '20200522', 'Q2'),
 (20200508, '2020-05-08 00:00:00', 2020, 5, 8, '202005', '20200508', 'Q2'),
 (20200529, '2020-05-29 00:00:00', 2020, 5, 29, '202005', '20200529', 'Q2'),
 (20200507, '2020-05-07 00:00:00', 2020, 5, 7, '202005', '20200507', 'Q2'),
 (20200516, '2020-05-16 00:00:00', 2020, 5, 16, '202005', '20200516', 'Q2'),
 (20200515, '2020-05-15 00:00:00', 2020, 5, 15, '202005', '20200515', 'Q2'),
 (20200506, '2020-05-06 00:00:00', 2020, 5, 6, '202005', '20200506', 'Q2'),
 (20191022, '2019-10-22 00:00:00', 2019, 10, 22, '201910', '20191022', 'Q4'),
 (20191024, '2019-10-24 00:00:00', 2019, 10, 24, '201910', '20191024', 'Q4'),
 (20191021, '2019-10-21 00:00:00', 2019, 10, 21, '201910', '20191021', 'Q4'),
 (20191027, '2019-10-27 00:00:00', 2019, 10, 27, '201910', '20191027', 'Q4'),
 (20191026, '2019-10-26 00:00:00', 2019, 10, 26, '201910', '20191026', 'Q4'),
 (20191025, '2019-10-25 00:00:00', 2019, 10, 25, '201910', '20191025', 'Q4'),
 (20191028, '2019-10-28 00:00:00', 2019, 10, 28, '201910', '20191028', 'Q4'),
 (20191030, '2019-10-30 00:00:00', 2019, 10, 30, '201910', '20191030', 'Q4'),
 (20191029, '2019-10-29 00:00:00', 2019, 10, 29, '201910', '20191029', 'Q4'),
 (20191020, '2019-10-20 00:00:00', 2019, 10, 20, '201910', '20191020', 'Q4'),
 (20191101, '2019-11-01 00:00:00', 2019, 11, 1, '201911', '20191101', 'Q4'),
 (20191031, '2019-10-31 00:00:00', 2019, 10, 31, '201910', '20191031', 'Q4'),
 (20191102, '2019-11-02 00:00:00', 2019, 11, 2, '201911', '20191102', 'Q4'),
 (20191103, '2019-11-03 00:00:00', 2019, 11, 3, '201911', '20191103', 'Q4'),
 (20191023, '2019-10-23 00:00:00', 2019, 10, 23, '201910', '20191023', 'Q4'),
 (20191019, '2019-10-19 00:00:00', 2019, 10, 19, '201910', '20191019', 'Q4'),
 (20190803, '2019-08-03 00:00:00', 2019, 8, 3, '201908', '20190803', 'Q3'),
 (20190806, '2019-08-06 00:00:00', 2019, 8, 6, '201908', '20190806', 'Q3'),
 (20190805, '2019-08-05 00:00:00', 2019, 8, 5, '201908', '20190805', 'Q3'),
 (20190804, '2019-08-04 00:00:00', 2019, 8, 4, '201908', '20190804', 'Q3'),
 (20190807, '2019-08-07 00:00:00', 2019, 8, 7, '201908', '20190807', 'Q3'),
 (20190731, '2019-07-31 00:00:00', 2019, 7, 31, '201907', '20190731', 'Q3'),
 (20190730, '2019-07-30 00:00:00', 2019, 7, 30, '201907', '20190730', 'Q3'),
 (20190802, '2019-08-02 00:00:00', 2019, 8, 2, '201908', '20190802', 'Q3'),
 (20190801, '2019-08-01 00:00:00', 2019, 8, 1, '201908', '20190801', 'Q3'),
 (20190729, '2019-07-29 00:00:00', 2019, 7, 29, '201907', '20190729', 'Q3'),
 (20190727, '2019-07-27 00:00:00', 2019, 7, 27, '201907', '20190727', 'Q3'),
 (20190728, '2019-07-28 00:00:00', 2019, 7, 28, '201907', '20190728', 'Q3'),
 (20190424, '2019-04-24 00:00:00', 2019, 4, 24, '201904', '20190424', 'Q2'),
 (20190425, '2019-04-25 00:00:00', 2019, 4, 25, '201904', '20190425', 'Q2'),
 (20190428, '2019-04-28 00:00:00', 2019, 4, 28, '201904', '20190428', 'Q2'),
 (20190427, '2019-04-27 00:00:00', 2019, 4, 27, '201904', '20190427', 'Q2'),
 (20190501, '2019-05-01 00:00:00', 2019, 5, 1, '201905', '20190501', 'Q2'),
 (20190426, '2019-04-26 00:00:00', 2019, 4, 26, '201904', '20190426', 'Q2'),
 (20190422, '2019-04-22 00:00:00', 2019, 4, 22, '201904', '20190422', 'Q2'),
 (20190423, '2019-04-23 00:00:00', 2019, 4, 23, '201904', '20190423', 'Q2'),
 (20190502, '2019-05-02 00:00:00', 2019, 5, 2, '201905', '20190502', 'Q2'),
 (20190429, '2019-04-29 00:00:00', 2019, 4, 29, '201904', '20190429', 'Q2'),
 (20190430, '2019-04-30 00:00:00', 2019, 4, 30, '201904', '20190430', 'Q2'),
 (20190503, '2019-05-03 00:00:00', 2019, 5, 3, '201905', '20190503', 'Q2'),
 (20190504, '2019-05-04 00:00:00', 2019, 5, 4, '201905', '20190504', 'Q2'),
 (20190505, '2019-05-05 00:00:00', 2019, 5, 5, '201905', '20190505', 'Q2'),
 (20190506, '2019-05-06 00:00:00', 2019, 5, 6, '201905', '20190506', 'Q2'),
 (20190421, '2019-04-21 00:00:00', 2019, 4, 21, '201904', '20190421', 'Q2'),
 (20190409, '2019-04-09 00:00:00', 2019, 4, 9, '201904', '20190409', 'Q2'),
 (20190408, '2019-04-08 00:00:00', 2019, 4, 8, '201904', '20190408', 'Q2'),
 (20190410, '2019-04-10 00:00:00', 2019, 4, 10, '201904', '20190410', 'Q2'),
 (20190411, '2019-04-11 00:00:00', 2019, 4, 11, '201904', '20190411', 'Q2'),
 (20190412, '2019-04-12 00:00:00', 2019, 4, 12, '201904', '20190412', 'Q2'),
 (20190413, '2019-04-13 00:00:00', 2019, 4, 13, '201904', '20190413', 'Q2'),
 (20190415, '2019-04-15 00:00:00', 2019, 4, 15, '201904', '20190415', 'Q2'),
 (20190417, '2019-04-17 00:00:00', 2019, 4, 17, '201904', '20190417', 'Q2'),
 (20190407, '2019-04-07 00:00:00', 2019, 4, 7, '201904', '20190407', 'Q2'),
 (20190406, '2019-04-06 00:00:00', 2019, 4, 6, '201904', '20190406', 'Q2'),
 (20190414, '2019-04-14 00:00:00', 2019, 4, 14, '201904', '20190414', 'Q2'),
 (20190418, '2019-04-18 00:00:00', 2019, 4, 18, '201904', '20190418', 'Q2'),
 (20190416, '2019-04-16 00:00:00', 2019, 4, 16, '201904', '20190416', 'Q2'),
 (20190405, '2019-04-05 00:00:00', 2019, 4, 5, '201904', '20190405', 'Q2'),
 (20190420, '2019-04-20 00:00:00', 2019, 4, 20, '201904', '20190420', 'Q2'),
 (20190419, '2019-04-19 00:00:00', 2019, 4, 19, '201904', '20190419', 'Q2'),
 (20190404, '2019-04-04 00:00:00', 2019, 4, 4, '201904', '20190404', 'Q2'),
 (20200316, '2020-03-16 00:00:00', 2020, 3, 16, '202003', '20200316', 'Q1'),
 (20200417, '2020-04-17 00:00:00', 2020, 4, 17, '202004', '20200417', 'Q2'),
 (20200413, '2020-04-13 00:00:00', 2020, 4, 13, '202004', '20200413', 'Q2'),
 (20200419, '2020-04-19 00:00:00', 2020, 4, 19, '202004', '20200419', 'Q2'),
 (20200428, '2020-04-28 00:00:00', 2020, 4, 28, '202004', '20200428', 'Q2'),
 (20200502, '2020-05-02 00:00:00', 2020, 5, 2, '202005', '20200502', 'Q2'),
 (20200430, '2020-04-30 00:00:00', 2020, 4, 30, '202004', '20200430', 'Q2'),
 (20200501, '2020-05-01 00:00:00', 2020, 5, 1, '202005', '20200501', 'Q2'),
 (20200418, '2020-04-18 00:00:00', 2020, 4, 18, '202004', '20200418', 'Q2'),
 (20200421, '2020-04-21 00:00:00', 2020, 4, 21, '202004', '20200421', 'Q2'),
 (20200424, '2020-04-24 00:00:00', 2020, 4, 24, '202004', '20200424', 'Q2'),
 (20200420, '2020-04-20 00:00:00', 2020, 4, 20, '202004', '20200420', 'Q2'),
 (20200422, '2020-04-22 00:00:00', 2020, 4, 22, '202004', '20200422', 'Q2'),
 (20200426, '2020-04-26 00:00:00', 2020, 4, 26, '202004', '20200426', 'Q2'),
 (20200425, '2020-04-25 00:00:00', 2020, 4, 25, '202004', '20200425', 'Q2'),
 (20200427, '2020-04-27 00:00:00', 2020, 4, 27, '202004', '20200427', 'Q2'),
 (20200423, '2020-04-23 00:00:00', 2020, 4, 23, '202004', '20200423', 'Q2'),
 (20200429, '2020-04-29 00:00:00', 2020, 4, 29, '202004', '20200429', 'Q2'),
 (20200503, '2020-05-03 00:00:00', 2020, 5, 3, '202005', '20200503', 'Q2'),
 (20200315, '2020-03-15 00:00:00', 2020, 3, 15, '202003', '20200315', 'Q1'),
 (20200505, '2020-05-05 00:00:00', 2020, 5, 5, '202005', '20200505', 'Q2'),
 (20200314, '2020-03-14 00:00:00', 2020, 3, 14, '202003', '20200314', 'Q1'),
 (20200416, '2020-04-16 00:00:00', 2020, 4, 16, '202004', '20200416', 'Q2'),
 (20200504, '2020-05-04 00:00:00', 2020, 5, 4, '202005', '20200504', 'Q2'),
 (20200317, '2020-03-17 00:00:00', 2020, 3, 17, '202003', '20200317', 'Q1'),
 (20200328, '2020-03-28 00:00:00', 2020, 3, 28, '202003', '20200328', 'Q1'),
 (20200404, '2020-04-04 00:00:00', 2020, 4, 4, '202004', '20200404', 'Q2'),
 (20200407, '2020-04-07 00:00:00', 2020, 4, 7, '202004', '20200407', 'Q2'),
 (20200312, '2020-03-12 00:00:00', 2020, 3, 12, '202003', '20200312', 'Q1'),
 (20200318, '2020-03-18 00:00:00', 2020, 3, 18, '202003', '20200318', 'Q1'),
 (20200309, '2020-03-09 00:00:00', 2020, 3, 9, '202003', '20200309', 'Q1'),
 (20200310, '2020-03-10 00:00:00', 2020, 3, 10, '202003', '20200310', 'Q1'),
 (20200320, '2020-03-20 00:00:00', 2020, 3, 20, '202003', '20200320', 'Q1'),
 (20200313, '2020-03-13 00:00:00', 2020, 3, 13, '202003', '20200313', 'Q1'),
 (20200411, '2020-04-11 00:00:00', 2020, 4, 11, '202004', '20200411', 'Q2'),
 (20200412, '2020-04-12 00:00:00', 2020, 4, 12, '202004', '20200412', 'Q2'),
 (20200326, '2020-03-26 00:00:00', 2020, 3, 26, '202003', '20200326', 'Q1'),
 (20200321, '2020-03-21 00:00:00', 2020, 3, 21, '202003', '20200321', 'Q1'),
 (20200319, '2020-03-19 00:00:00', 2020, 3, 19, '202003', '20200319', 'Q1'),
 (20200323, '2020-03-23 00:00:00', 2020, 3, 23, '202003', '20200323', 'Q1'),
 (20200308, '2020-03-08 00:00:00', 2020, 3, 8, '202003', '20200308', 'Q1'),
 (20200403, '2020-04-03 00:00:00', 2020, 4, 3, '202004', '20200403', 'Q2'),
 (20200329, '2020-03-29 00:00:00', 2020, 3, 29, '202003', '20200329', 'Q1'),
 (20200311, '2020-03-11 00:00:00', 2020, 3, 11, '202003', '20200311', 'Q1'),
 (20200307, '2020-03-07 00:00:00', 2020, 3, 7, '202003', '20200307', 'Q1'),
 (20200322, '2020-03-22 00:00:00', 2020, 3, 22, '202003', '20200322', 'Q1'),
 (20200324, '2020-03-24 00:00:00', 2020, 3, 24, '202003', '20200324', 'Q1'),
 (20200415, '2020-04-15 00:00:00', 2020, 4, 15, '202004', '20200415', 'Q2'),
 (20200331, '2020-03-31 00:00:00', 2020, 3, 31, '202003', '20200331', 'Q1'),
 (20200410, '2020-04-10 00:00:00', 2020, 4, 10, '202004', '20200410', 'Q2'),
 (20200406, '2020-04-06 00:00:00', 2020, 4, 6, '202004', '20200406', 'Q2'),
 (20200414, '2020-04-14 00:00:00', 2020, 4, 14, '202004', '20200414', 'Q2'),
 (20200405, '2020-04-05 00:00:00', 2020, 4, 5, '202004', '20200405', 'Q2'),
 (20200330, '2020-03-30 00:00:00', 2020, 3, 30, '202003', '20200330', 'Q1'),
 (20200325, '2020-03-25 00:00:00', 2020, 3, 25, '202003', '20200325', 'Q1'),
 (20200402, '2020-04-02 00:00:00', 2020, 4, 2, '202004', '20200402', 'Q2'),
 (20200408, '2020-04-08 00:00:00', 2020, 4, 8, '202004', '20200408', 'Q2'),
 (20200327, '2020-03-27 00:00:00', 2020, 3, 27, '202003', '20200327', 'Q1'),
 (20200401, '2020-04-01 00:00:00', 2020, 4, 1, '202004', '20200401', 'Q2'),
 (20191217, '2019-12-17 00:00:00', 2019, 12, 17, '201912', '20191217', 'Q4'),
 (20191218, '2019-12-18 00:00:00', 2019, 12, 18, '201912', '20191218', 'Q4'),
 (20191219, '2019-12-19 00:00:00', 2019, 12, 19, '201912', '20191219', 'Q4'),
 (20191220, '2019-12-20 00:00:00', 2019, 12, 20, '201912', '20191220', 'Q4'),
 (20191221, '2019-12-21 00:00:00', 2019, 12, 21, '201912', '20191221', 'Q4'),
 (20191223, '2019-12-23 00:00:00', 2019, 12, 23, '201912', '20191223', 'Q4'),
 (20191227, '2019-12-27 00:00:00', 2019, 12, 27, '201912', '20191227', 'Q4'),
 (20191228, '2019-12-28 00:00:00', 2019, 12, 28, '201912', '20191228', 'Q4'),
 (20191226, '2019-12-26 00:00:00', 2019, 12, 26, '201912', '20191226', 'Q4'),
 (20191222, '2019-12-22 00:00:00', 2019, 12, 22, '201912', '20191222', 'Q4'),
 (20191224, '2019-12-24 00:00:00', 2019, 12, 24, '201912', '20191224', 'Q4'),
 (20191225, '2019-12-25 00:00:00', 2019, 12, 25, '201912', '20191225', 'Q4'),
 (20191229, '2019-12-29 00:00:00', 2019, 12, 29, '201912', '20191229', 'Q4'),
 (20191230, '2019-12-30 00:00:00', 2019, 12, 30, '201912', '20191230', 'Q4'),
 (20200101, '2020-01-01 00:00:00', 2020, 1, 1, '202001', '20200101', 'Q1'),
 (20191215, '2019-12-15 00:00:00', 2019, 12, 15, '201912', '20191215', 'Q4'),
 (20191231, '2019-12-31 00:00:00', 2019, 12, 31, '201912', '20191231', 'Q4'),
 (20191216, '2019-12-16 00:00:00', 2019, 12, 16, '201912', '20191216', 'Q4'),
 (20191210, '2019-12-10 00:00:00', 2019, 12, 10, '201912', '20191210', 'Q4'),
 (20190723, '2019-07-23 00:00:00', 2019, 7, 23, '201907', '20190723', 'Q3'),
 (20190722, '2019-07-22 00:00:00', 2019, 7, 22, '201907', '20190722', 'Q3'),
 (20190724, '2019-07-24 00:00:00', 2019, 7, 24, '201907', '20190724', 'Q3'),
 (20190726, '2019-07-26 00:00:00', 2019, 7, 26, '201907', '20190726', 'Q3'),
 (20190725, '2019-07-25 00:00:00', 2019, 7, 25, '201907', '20190725', 'Q3'),
 (20190313, '2019-03-13 00:00:00', 2019, 3, 13, '201903', '20190313', 'Q1'),
 (20190721, '2019-07-21 00:00:00', 2019, 7, 21, '201907', '20190721', 'Q3'),
 (20191015, '2019-10-15 00:00:00', 2019, 10, 15, '201910', '20191015', 'Q4'),
 (20191014, '2019-10-14 00:00:00', 2019, 10, 14, '201910', '20191014', 'Q4'),
 (20191013, '2019-10-13 00:00:00', 2019, 10, 13, '201910', '20191013', 'Q4'),
 (20191017, '2019-10-17 00:00:00', 2019, 10, 17, '201910', '20191017', 'Q4'),
 (20191016, '2019-10-16 00:00:00', 2019, 10, 16, '201910', '20191016', 'Q4'),
 (20191018, '2019-10-18 00:00:00', 2019, 10, 18, '201910', '20191018', 'Q4'),
 (20191010, '2019-10-10 00:00:00', 2019, 10, 10, '201910', '20191010', 'Q4'),
 (20191009, '2019-10-09 00:00:00', 2019, 10, 9, '201910', '20191009', 'Q4'),
 (20190930, '2019-09-30 00:00:00', 2019, 9, 30, '201909', '20190930', 'Q3'),
 (20191012, '2019-10-12 00:00:00', 2019, 10, 12, '201910', '20191012', 'Q4'),
 (20191114, '2019-11-14 00:00:00', 2019, 11, 14, '201911', '20191114', 'Q4'),
 (20191110, '2019-11-10 00:00:00', 2019, 11, 10, '201911', '20191110', 'Q4'),
 (20191116, '2019-11-16 00:00:00', 2019, 11, 16, '201911', '20191116', 'Q4'),
 (20191118, '2019-11-18 00:00:00', 2019, 11, 18, '201911', '20191118', 'Q4'),
 (20191117, '2019-11-17 00:00:00', 2019, 11, 17, '201911', '20191117', 'Q4'),
 (20191109, '2019-11-09 00:00:00', 2019, 11, 9, '201911', '20191109', 'Q4'),
 (20191106, '2019-11-06 00:00:00', 2019, 11, 6, '201911', '20191106', 'Q4'),
 (20191108, '2019-11-08 00:00:00', 2019, 11, 8, '201911', '20191108', 'Q4'),
 (20191107, '2019-11-07 00:00:00', 2019, 11, 7, '201911', '20191107', 'Q4'),
 (20191113, '2019-11-13 00:00:00', 2019, 11, 13, '201911', '20191113', 'Q4'),
 (20191111, '2019-11-11 00:00:00', 2019, 11, 11, '201911', '20191111', 'Q4'),
 (20191112, '2019-11-12 00:00:00', 2019, 11, 12, '201911', '20191112', 'Q4'),
 (20191115, '2019-11-15 00:00:00', 2019, 11, 15, '201911', '20191115', 'Q4'),
 (20191119, '2019-11-19 00:00:00', 2019, 11, 19, '201911', '20191119', 'Q4'),
 (20200212, '2020-02-12 00:00:00', 2020, 2, 12, '202002', '20200212', 'Q1'),
 (20200227, '2020-02-27 00:00:00', 2020, 2, 27, '202002', '20200227', 'Q1'),
 (20200215, '2020-02-15 00:00:00', 2020, 2, 15, '202002', '20200215', 'Q1'),
 (20200229, '2020-02-29 00:00:00', 2020, 2, 29, '202002', '20200229', 'Q1'),
 (20200213, '2020-02-13 00:00:00', 2020, 2, 13, '202002', '20200213', 'Q1'),
 (20200220, '2020-02-20 00:00:00', 2020, 2, 20, '202002', '20200220', 'Q1'),
 (20200216, '2020-02-16 00:00:00', 2020, 2, 16, '202002', '20200216', 'Q1'),
 (20200224, '2020-02-24 00:00:00', 2020, 2, 24, '202002', '20200224', 'Q1'),
 (20200218, '2020-02-18 00:00:00', 2020, 2, 18, '202002', '20200218', 'Q1'),
 (20200301, '2020-03-01 00:00:00', 2020, 3, 1, '202003', '20200301', 'Q1'),
 (20200226, '2020-02-26 00:00:00', 2020, 2, 26, '202002', '20200226', 'Q1'),
 (20200223, '2020-02-23 00:00:00', 2020, 2, 23, '202002', '20200223', 'Q1'),
 (20200228, '2020-02-28 00:00:00', 2020, 2, 28, '202002', '20200228', 'Q1'),
 (20200225, '2020-02-25 00:00:00', 2020, 2, 25, '202002', '20200225', 'Q1'),
 (20200219, '2020-02-19 00:00:00', 2020, 2, 19, '202002', '20200219', 'Q1'),
 (20200221, '2020-02-21 00:00:00', 2020, 2, 21, '202002', '20200221', 'Q1'),
 (20200214, '2020-02-14 00:00:00', 2020, 2, 14, '202002', '20200214', 'Q1'),
 (20200222, '2020-02-22 00:00:00', 2020, 2, 22, '202002', '20200222', 'Q1'),
 (20200217, '2020-02-17 00:00:00', 2020, 2, 17, '202002', '20200217', 'Q1'),
 (20200302, '2020-03-02 00:00:00', 2020, 3, 2, '202003', '20200302', 'Q1'),
 (20200305, '2020-03-05 00:00:00', 2020, 3, 5, '202003', '20200305', 'Q1'),
 (20200304, '2020-03-04 00:00:00', 2020, 3, 4, '202003', '20200304', 'Q1'),
 (20200303, '2020-03-03 00:00:00', 2020, 3, 3, '202003', '20200303', 'Q1'),
 (20200306, '2020-03-06 00:00:00', 2020, 3, 6, '202003', '20200306', 'Q1'),
 (20200211, '2020-02-11 00:00:00', 2020, 2, 11, '202002', '20200211', 'Q1'),
 (20190831, '2019-08-31 00:00:00', 2019, 8, 31, '201908', '20190831', 'Q3'),
 (20190901, '2019-09-01 00:00:00', 2019, 9, 1, '201909', '20190901', 'Q3'),
 (20190830, '2019-08-30 00:00:00', 2019, 8, 30, '201908', '20190830', 'Q3'),
 (20190902, '2019-09-02 00:00:00', 2019, 9, 2, '201909', '20190902', 'Q3'),
 (20190903, '2019-09-03 00:00:00', 2019, 9, 3, '201909', '20190903', 'Q3'),
 (20190904, '2019-09-04 00:00:00', 2019, 9, 4, '201909', '20190904', 'Q3'),
 (20190906, '2019-09-06 00:00:00', 2019, 9, 6, '201909', '20190906', 'Q3'),
 (20190905, '2019-09-05 00:00:00', 2019, 9, 5, '201909', '20190905', 'Q3'),
 (20190122, '2019-01-22 00:00:00', 2019, 1, 22, '201901', '20190122', 'Q1'),
 (20190120, '2019-01-20 00:00:00', 2019, 1, 20, '201901', '20190120', 'Q1'),
 (20190121, '2019-01-21 00:00:00', 2019, 1, 21, '201901', '20190121', 'Q1'),
 (20190123, '2019-01-23 00:00:00', 2019, 1, 23, '201901', '20190123', 'Q1'),
 (20190125, '2019-01-25 00:00:00', 2019, 1, 25, '201901', '20190125', 'Q1'),
 (20190126, '2019-01-26 00:00:00', 2019, 1, 26, '201901', '20190126', 'Q1'),
 (20190128, '2019-01-28 00:00:00', 2019, 1, 28, '201901', '20190128', 'Q1'),
 (20190124, '2019-01-24 00:00:00', 2019, 1, 24, '201901', '20190124', 'Q1'),
 (20190130, '2019-01-30 00:00:00', 2019, 1, 30, '201901', '20190130', 'Q1'),
 (20190131, '2019-01-31 00:00:00', 2019, 1, 31, '201901', '20190131', 'Q1'),